### ISSUE TITLE
Comparison with xsel

### ISSUE THREAD

**Issue by phiresky** [niedzielski/clipboard#1]
xsel (https://github.com/kfish/xsel) seems very similar and is part of the repositories of most distros

**Comment by niedzielski** [comment]
Hm, XSel looks amazing. cb is probably totally redundant anywhere you can get it. It sounded like in (#3) that Wayland is a place you have to use some XSel alternative. I'll add a note under the "why you don't need cb" section and also update the dependencies for Wayland to mention wl-clipboard which I forgot to do.

Rest assured, any other tool will do but I encourage you to explore using the clipboard to work across the CLI and GUIs.

Thanks, @phiresky!
