### ISSUE TITLE
Wayland not supported/detected

### ISSUE THREAD

**Issue by elmarsto** [niedzielski/clipboard#3]
Wayland compositor on linux does not use xclip/xsel, it uses `wl-copy`, `wl-paste`.  `xclip` and `xsel` might not even be installed.

The provided `cb` script as of this writing does not detect this, and I am reporting it nonfunctional on (at least) NixOS 22.11 with Wayland enabled.

It is likely other Linux distros-supporting-wayland will also experience this bug.

**Comment by niedzielski** [comment]
Fixed by you! #4
